// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxgisaujwvvttitpsedr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Z2lzYXVqd3Z2dHRpdHBzZWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTkyMzcsImV4cCI6MjA2NTgzNTIzN30.R1GRoA72ExG7EZkR3xKIY7Uu5T2PFduPg76faHgL7Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);